services:
  database-pg:
    image: postgres:16.2-alpine3.19
    volumes:
      - database-pg:/var/lib/postgresql/data
      - ./certificates/postgresql/server.crt:/var/lib/postgresql/server.crt
      - ./certificates/postgresql/server.key:/var/lib/postgresql/server.key
    ports:
      - 4545:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS="-A md5"
    env_file:
      - ./.env
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
volumes:
  database-pg:
    driver: 
      local